language: r
r:
  - 3.5.0
sudo: false
cache:
  packages: true
latex: false
branches:
  only:
    - master
    - release
    - stable

pandoc_version: 2.2.3.2

git:
  depth: 5
  submodules: false
  lfs_skip_smudge: true
  
repos:
  CRAN: https://cloud.r-project.org
  RForge: https://r-forge.r-project.org

addons:
  apt:
    sources:
      - sourceline: ppa:opencpu/imagemagick
    packages:
      - ghostscript
      - imagemagick
      - optipng
      - fonts-inconsolata
      - libgit2-dev
      - libudunits2-dev 
      - libgdal-dev 
      - libgeos-dev 
      - libproj-dev 

before_install:
  - npm install netlify-cli -g
#  - curl -fLo /tmp/tinytex.tar.gz https://travis-bin.yihui.name/tinytex.tar.gz
#  - tar xzf /tmp/tinytex.tar.gz -C /$HOME
#  - export PATH=/$HOME/.TinyTeX/bin/x86_64-linux:$PATH
#  - Rscript -e 'tinytex::tlmgr_install(readLines("latex/TeXLive.pkgs"))'
#  - tlmgr install $(cat latex/TeXLive.pkgs | tr '\n' ' ') || true
#  - mkdir -p /$HOME/.fonts
#  - cp -r fonts/* /$HOME/.fonts/
#  - fc-cache -fsv
#  - fc-list :lang=en-us | sort
#  - fc-list :lang=zh-cn | sort
#  - du -h -d 1

before_script:
  - Rscript -e 'update.packages(lib.loc = .libPaths()[1], ask = FALSE)'

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", config_file = "_bookdown_skeleton.yml")'

after_success:
  - netlify deploy -t $NETLIFY_PAT
