language: r
sudo: false
cache:
  packages: true
latex: false
branches:
  only:
    - master
    - release
    - stable

pandoc_version: 2.2.3.2

git:
  depth: 5
  submodules: false
  
repos:
  CRAN: https://cloud.r-project.org
  RForge: https://r-forge.r-project.org

r_github_packages:
  - jimhester/covr
  
addons:
  apt:
    sources:
      - sourceline: ppa:opencpu/imagemagick
    packages:
      - ghostscript
      - imagemagick
      - optipng
      - fonts-inconsolata
      - libgit2-dev
      - libudunits2-dev 
      - libgdal-dev 
      - libgeos-dev 
      - libproj-dev 

before_install:
  - npm install netlify-cli -g
  - curl -fLo /tmp/tinytex.tar.gz https://travis-bin.yihui.name/tinytex.tar.gz
  - tar xzf /tmp/tinytex.tar.gz -C /$HOME
  - export PATH=/$HOME/.TinyTeX/bin/x86_64-linux:$PATH
  - Rscript -e 'tinytex::tlmgr_install(readLines("latex/TeXLive.pkgs"))'
#  - tlmgr install $(cat latex/TeXLive.pkgs | tr '\n' ' ') || true
  - mkdir -p /$HOME/.fonts
  - cp -r fonts/* /$HOME/.fonts/
  - fc-cache -fsv
  - fc-list :lang=en-us | sort
  - fc-list :lang=zh-cn | sort

before_script:
  - Rscript -e 'update.packages(lib.loc = .libPaths()[1], ask = FALSE)'

script:
  - make gitbook

after_success:
  - make pdf
  - netlify deploy -t $NETLIFY_PAT
  - travis_wait 30 Rscript -e 'covr::codecov()'
 